//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorldChaCha
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Material()
        {
            this.PossibleSuppliers = new HashSet<PossibleSuppliers>();
            this.NecessaryMaterials = new HashSet<NecessaryMaterials>();
        }
    
        public int IDМатериала { get; set; }
        public string Наименование { get; set; }
        public string ТипМатериала { get; set; }
        public byte[] ИзображениеМатериала { get; set; }
        public Nullable<decimal> Цена { get; set; }
        public Nullable<int> КолНаСкладе { get; set; }
        public Nullable<int> МинКолНаСкладе { get; set; }
        public Nullable<int> КолУпаковки { get; set; }
        public string ЕдиницаИзм { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PossibleSuppliers> PossibleSuppliers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NecessaryMaterials> NecessaryMaterials { get; set; }
    }
}
